// Authentication
export const SET_AUTHED_USER = 'SET_AUTHED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// Loading
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';

// Manage Errors
export const LOG_ERROR = 'LOG_ERROR';

export const FETCH_GENRE_BOOKS = 'FETCH_GENRE_BOOKS';

export const FETCH_BOOKS_CATEGORIES = 'FETCH_BOOKS_CATEGORIES';

export const FETCH_NEW_RELEASE = 'FETCH_NEW_RELEASE';

export const FETCH_POPULAR_BOOKS = 'FETCH_POPULAR_BOOKS';

export const FETCH_BOOK_INFO = 'FETCH_BOOK_INFO';

export const FETCH_AUTHOR = 'FETCH_AUTHOR';

export const FETCH_DASHBOARD_STATS = 'FETCH_DASHBOARD_STATS';

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';

export const UPDATE_USER = 'UPDATE_USER';

export const FETCH_USER_ORDERS = 'FETCH_USER_ORDERS';
export const FETCH_USER_BOOKS = 'FETCH_USER_BOOKS';
export const FETCH_USER_ADDRESSES = 'FETCH_USER_ADDRESSES';
