const serverLink = 'https://twese.co/';

export const ImageLink = `${serverLink}GenreIcon/`;
export const BookCover = `${serverLink}BookCover/`;
export const UserProfile = `${serverLink}UserProfile/`;
export const ReadBookLink = `${serverLink}BookFile/`;

export const colorsPool = [
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
  '#fed6e0',
  '#c3fdbc',
  '#c6e1ff',
  '#ffedbd',
  '#bcf7ff',
];
export const selectColor = () => {
  const item = colorsPool[Math.floor(Math.random() * colorsPool.length)];
  return item;
};

export const genders = [
  { id: 'male', name: 'Male' },
  { id: 'female', name: 'Female' },
  { id: 'trans-man', name: 'Trans man' },
  { id: 'trans-woman', name: 'Trans woman' },
  { id: 'non-binary', name: 'Non binary' },
  { id: 'gender-fluid', name: 'Gender fluid' },
  { id: 'not-applicable', name: 'Not applicable' },
];
